configurations:
    - id: project-a
      name: Project A configuration
      description: The configuration used in project A
      qodanaYaml: config-a/qodana.yaml

    - id: project-b
      name: Project B configuration
      description: The configuration used in project B
      qodanaYaml: config-b/qodana.yaml
        
